project:
  type: website
  output-dir: docs

website:
  title: "Welcome to Jonathan's website. Take a look around, there's not much to see."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



